### ISSUE TITLE
 Qr codes didn't match code

### ISSUE THREAD

**Issue by Joo12345** [Joshua-McMorran/5CS024-openDayApp#1]
Hi Guys,
Qr codes didn't match code.

The developers ps fix this.

tnks

**Comment by Joo12345** [comment]
Hi Guys,

The error has been fixed.
Good job for fixing the error 


O Julian Osondu

[Fixed bug where Qr codes didnt match code.docx](https://github.com/Joshua-McMorran/5CS024-openDayApp/files/3047187/Fixed.bug.where.Qr.codes.didnt.match.code.docx)

**Comment by Rebaz111** [comment]
well done developers to match code.
thank you guys

**Comment by Joo12345** [comment]
Hi Guys,

The bug issues has been fixed.
You can test the code, and if you notice any further issues kindly, let me know as soon as possible.

Thanks 
Julian Osondu
